### PR TITLE
Set correct test class namespaces

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log

- Set `pull_request` trigger on GitHub action.
- Setting correct test class namespace for these PHP files.
- Add EOF for files on tests folder.

### CODE REVIEW

**Review by g105b — APPROVED** [review]
Good catch :+1:

**Comment by g105b** [comment]
Thanks for your contribution, my bad for introducing incorrect namespaces. 

May I ask how you're using this library?

**Comment by peter279k** [comment]
Thanks for your reply. I just use some Linux commands (such as sed and grep) to help me to find and replace these testing class namespaces.

**Comment by g105b** [comment]
I'm interested in hearing how you are using this library, if you care to share? I hope it's helpful to you, but this repository hasn't been used by many people outside of WebEngine.

**Comment by peter279k** [comment]
> 
> 
> I'm interested in hearing how you are using this library, if you care to share? I hope it's helpful to you, but this repository hasn't been used by many people outside of WebEngine.

Actually, there's no library :). If you're interseted in, I will consider letting these commands be a shell script and publish on my GitHub profile.

**Comment by g105b** [comment]
Cool - I'm always interested in hearing how people are using PhpGt repositories. Have a good day.

**Comment by peter279k** [comment]
BTW, I also use the [rector](https://github.com/rectorphp/rector) to check some stuffs with specific rules.

And it can also help me to check whether the class namespaces are same as that class namespace defined on `composer.json` file during rector running :).

**Comment by g105b** [comment]
Cool, I will look into it. Thanks.

**Pull request merged**
